name: 'Dispatch CI/CD Events'
description: 'Use this actions to trigger other workflows'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${DEPLOY_TOKEN}" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches \
          -d '{"event_type":"gh_pages_deployed", "client_payload": { "version": "1.0.0"}}'
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      shell: bash
    - run: ${{ github.action_path }}/api.sh
      shell: bash
