name: 'Dispatch CI/CD Events'
description: 'Use this actions to trigger other workflows'
inputs:
  event_type:  # id of input
    description: 'Event Type to Trigger'
    required: true
    default: 'none'
  token:  # id of input
    description: 'Deploy Token'
    required: true
    default: 'none'
outputs:
  event-info:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.event_type }}
runs:
  using: "composite"
  steps:
    - run: echo Event is ${{ inputs.event_type }}.
      name: Event Type
      shell: bash
    - id: dispatch-events
      name: Dispatch Events
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${DEPLOY_TOKEN}" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches \
          -d '{"event_type":"${{ inputs.event_type }}", "client_payload": { "version": "1.0.0"}}'
      env:
        DEPLOY_TOKEN: ${{ inputs.token }}
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=event_type::${{ inputs.event_type }}"
      shell: bash
    - run: ${{ github.action_path }}/api.sh
      name: Bash Script
      shell: bash
