version: '3.3'
services:
  msl-build:
    build:
      context: .
      dockerfile: devops/docker/Dockerfile
      args:
        - APP_NAME=msl-preview
    restart: always
    ports:
      - 8001:8000
    deploy:
      replicas: 1
  msl-preview:
    build:
      context: .
      dockerfile: devops/docker/preview.Dockerfile
      args:
        - APP_NAME=msl-build
    restart: always
    ports:
      - 9001:9000
    deploy:
      replicas: 1
