type MslSeasonsJsonTeams implements Node {
  owners: [MslPlayersJson] @link(by: "player_id")
  players: [MslPlayersJson] @link(by: "player_id")
  team: MslTeamsJson @link(by: "team_id")
}

type MslSchedulesJsonStatsHome implements Node {
		team: MslTeamsJson @link(by: "team_id")
}

type MslSchedulesJsonStatsAway implements Node {
		team: MslTeamsJson @link(by: "team_id")
}

type MslSchedulesJsonReferees implements Node {
  player: MslPlayersJson @link(by: "player_id")
  team: MslTeamsJson @link(by: "team_id")
}


type MslTeamsJson implements Node {
  seasons: [MslSeasonsJson] @link(by: "team.team_id", from: "team_id")
}

type MslSeasonsJson implements Node {
  mos: [MslPlayersJson] @link(by: "player_id")
  schedules: [MslSchedulesJson] @link(by: "season.season_id", from: "season_id")
}

type MslSchedulesJson implements Node {
  season: MslSeasonsJson @link(by: "season")
}
