# union examples
# https://www.gatsbyjs.com/docs/schema-customization/#custom-interfaces-and-unions

interface TestJson {
  typeName: Int
  name: String
}

type Test1Json implements Node & TestJson {
	typeName: Int
	name: String
}

type Test2Json implements Node & TestJson {
	typeName: Int
	name: String
}
