# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD
on:
  push:
    branches: [gatsby]
    paths:
      - 'src/**'
      - '**.js'
      - 'static/**'
      - 'package.json'
      - '!lighthouserc.js'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Lint
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_lint'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    name: Unit Test
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Unit Test
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_unit_test'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  e2e-test:
    runs-on: ubuntu-latest
    name: E2E Test
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Line
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_e2e_test'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  lhci-build:
    runs-on: ubuntu-latest
    needs: e2e-test
    name: Light House Build
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Deploy
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_lhci_build'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: e2e-test
    environment:
      name: dev
      url: https://tomalex0.github.io/morningsoccerleague.github.io
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Line
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_deploy'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  release:
    runs-on: ubuntu-latest
    name: Release
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Line
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_release'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  lhci-url:
    runs-on: ubuntu-latest
    needs: deploy
    name: Light House Url
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Deploy
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_lhci_url'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
