# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on: [push,pull_request,workflow_dispatch]
jobs:
  composite:
    name: Composite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: composite-id
        name: Composite Actions
        uses: ./.github/actions/dispatch
        with:
          event_type: 'gh_pages_deployed'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - id: composite-id
        name: Lint
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_lint'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    name: Lint
    steps:
      - id: composite-id
        name: Unit Test
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_unit_test'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  e2e-test:
    runs-on: ubuntu-latest
    name: E2E Test
    needs: unit-test
    steps:
      - id: composite-id
        name: Line
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_e2e_test'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: e2e-test
    environment:
      name: dev
      url: https://tomalex0.github.io/morningsoccerleague.github.io
    steps:
      - id: composite-id
        name: Line
        uses: ./.github/actions/dispatch
        with:
          event_type: 'msl_deploy'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
  lhci:
    runs-on: ubuntu-latest
    needs: deploy
    name: Light House
    steps:
      - id: composite-id
        name: Deploy
        uses: ./.github/actions/dispatch
        with:
          event_type: 'gh_pages_deployed'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo Event Type ${{ steps.composite-id.outputs.event-info }}
        shell: bash
