# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on: [push,pull_request,workflow_dispatch]
jobs:
  composite:
    name: Composite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: foo
        name: Composite Actions
        uses: ./.github/actions/dispatch
        with:
          event_type: 'gh_pages_deployed'
          token: ${{ secrets.DEPLOY_TOKEN }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Lint
        run: echo "Lint"
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    name: Unit Test
    steps:
      - name: Unit Test
        id: unit_test
        run: echo "Unit Test"
  e2e:
    runs-on: ubuntu-latest
    needs: unit-test
    name: E2E Test
    steps:
      - name: UI Test
        id: ui_test
        run: echo "UI Test"
  deploy:
    runs-on: ubuntu-latest
    needs: e2e
    name: Deploy
    environment:
      name: dev
      url: https://tomalex0.github.io/morningsoccerleague.github.io/
    steps:
      - name: Deploy
        run: echo "Deploy"
  lhci:
    runs-on: ubuntu-latest
    needs: deploy
    name: Light House
    steps:
      - name: Light House
        run: echo "Light House"
