name: Github Pages Deploy CI
on:
  push:
    branches: [gatsby]
    paths:
      - 'src/**'
      - '**.js'
      - 'static/**'
      - 'package.json'
      - '!lighthouserc.js'
  workflow_dispatch:
jobs:
  ghpages:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache Npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Build Application
        run: |
          npm run build -- --prefix-paths  --profile --log-pages --write-to-file
        env:
          PATH_PREFIX: morningsoccerleague.github.io
          SITE_URL: https://tomalex0.github.io
      - name: Deploy to gh-pages
        run: |
          npx gh-pages -d public -b gh-pages -u "github-actions-bot <support+actions@github.com>" -r https://git:${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      - name: Deployed Event Trigger
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: ${DEPLOY_TOKEN}" \
            https://api.github.com/repos/tomalex0/morningsoccerleague.github.io/dispatches \
            -d '{"event_type":"gh_pages_deployed", "client_payload": { "version": "1.0.0"}}'
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  lhci:
    needs: ghpages
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --config=./lighthouserc-url.js
